#! usr/bin/python3

"""
   To visualize the tree generated by iqtree
   
"""

# import the Tree feature from ete3 toolkit using command pip installed ete3
from ete3 import Tree, NodeStyle, TreeStyle 

t = Tree("Alignment2.fas.treefile") #reading treefile generated using iqtree
ts = TreeStyle()
ts.show_leaf_name = True #show the leaf names 
ts.show_branch_length = True #show the tree branch length
ts.show_branch_support = True #show the branch support
t.render("mytree.png", tree_style=ts) #This render the phylogenetic tree in to png file
t.show(tree_style=ts) # this help to show the final tree in a GUI

# To prints the tree without any customization
print(t) 

# To write a new file as an output of nodes
t.write(format=1, outfile="Alignment2.fas_tree.mw") 
 

# To print the image of phylogenetic tree
#t.render("Phylogenetic_tree.png")
