#! usr/bin/python3

"""
   To visualize the tree generated by iqtree
   
"""

# import the Tree feature from ete3 toolkit using command pip installed ete3
from ete3 import Tree 

t = Tree("Alignment2.fas.treefile") #reading file generated using iqtree

# To prints the tree without any customization
print(t) 

# To write a new file as an output of nodes
t.write(format=1, outfile="Alignment2.fas_tree.mw") 
